routes/web.php
<?php

use App\Http\Controllers\Api\ScheduleStudentController;
use App\Http\Controllers\Auth\GoogleController;
use App\Http\Controllers\BalanceController;
use App\Http\Controllers\HomeController;
use App\Http\Controllers\PermissionController;
use App\Http\Controllers\RoleController;
use App\Http\Controllers\UserController;
use App\Http\Controllers\CategoryController;
use App\Http\Controllers\GradeController;
use App\Http\Controllers\HospitalController;
use App\Http\Controllers\LevelController;
use App\Http\Controllers\ProductController;
use App\Http\Controllers\ScheduleController;
use App\Http\Controllers\QuotaController;
use App\Http\Controllers\StaseController;
use App\Http\Controllers\StudentController;
use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Auth::routes(['register' => false]);

Route::get('auth/google', [GoogleController::class, 'redirectToGoogle'])->name('auth.google');
Route::get('auth/google/callback', [GoogleController::class, 'handleGoogleCallback']);

Route::group(['middleware' => ['auth']], function () {
    Route::get('', [HomeController::class, 'index'])->name('home');
    Route::get('home/report', [HomeController::class, 'report'])->name('home.report');

    Route::patch('user/login-as/{id}', [UserController::class, 'loginAs'])->name('user.login-as');
    Route::get('report', [HomeController::class, 'report'])->name('home.report');
    Route::resource('user', UserController::class);
    Route::resource('permission', PermissionController::class);
    Route::resource('role', RoleController::class);
    Route::resource('student', StudentController::class);
    Route::resource('hospital', HospitalController::class);
    Route::resource('stase', StaseController::class);
    Route::resource('schedule', ScheduleController::class);
    Route::resource('level', LevelController::class);
    Route::resource('grade', GradeController::class);
    Route::post('schedule/select-student', [ScheduleController::class, 'select_student'])->name('schedule.select-student');
    Route::post('schedule/update-schedule-student/{id}', [ScheduleController::class, 'update_schedule_student'])->name('schedule.update-schedule-student');
    Route::get('schedule/{id}/data', [ScheduleController::class, 'data'])->name('schedule.data');
    Route::post('schedule/{id}/drag', [ScheduleController::class, 'drag'])->name('schedule.drag');
    Route::get('schedule/{id}/report', [ScheduleController::class, 'report'])->name('schedule.report');
    Route::get('schedule/{schedule_id}/report/{student_id}', [ScheduleController::class, 'reportDetail'])->name('schedule.report-detail');
    Route::get('schedule/{id}/fullscreen', [ScheduleController::class, 'fullscreen'])->name('schedule.fullscreen');

    Route::resource('quota', QuotaController::class);
    Route::post('students/import', [StudentController::class, 'import'])->name('students.import');

    Route::get('stase/{id}/student-list', [StaseController::class, 'studentList'])->name('stase.student-list');
    Route::get('level/schedule/{id}/student-list', [LevelController::class, 'studentList'])->name('level.student-list');
    Route::get('students/export', [StudentController::class, 'export'])->name('students.export');
    Route::get('schedules/export/{id}', [ScheduleController::class, 'export'])->name('schedules.export');

    //api
    Route::get('api/hospital', [HospitalController::class, 'index'])->name('api.hospital.index');
    Route::get('api/stase', [StaseController::class, 'index'])->name('api.stase.index');
    Route::post('api/schedule-student/store', [ScheduleStudentController::class, 'store'])->name('api.schedule-student.store');
    Route::put('api/schedule-student/store-new-student', [ScheduleStudentController::class, 'storeNewStudent'])->name('api.schedule-student.store-new-student');
    Route::delete('api/schedule-student/{id}', [ScheduleStudentController::class, 'destroy'])->name('api.schedule-student.destroy');
    Route::put('api/schedule-student/{id}', [ScheduleStudentController::class, 'update'])->name('api.schedule-student.update');
});

Route::get('check-time', function () {
    return date('Y-m-d H:i:s');
});

app/Models/Hospital.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\SoftDeletes;

class Hospital extends Model
{
    use HasFactory, SoftDeletes;
    protected $fillable = [
        'name',
        'address',
        'color',
        'sequence',
    ];

    public function getLabels() {
        return [
            'name' => 'nama',
            'address' => 'alamat',
            'color' => 'warna',
            'sequence' => 'urutan'
        ];
    }

    public function quotas() {
        return $this->hasMany(Quota::class);
    }

    public function schedule_students() {
        return $this->hasMany(ScheduleStudent::class);
    }
}

app/Http/Controllers/Api/HospitalController.php
<?php

namespace App\Http\Controllers\Api;

use App\Http\Controllers\Controller;
use App\Models\Hospital;
use Illuminate\Http\Request;

class HospitalController extends Controller
{
    public function index() {
        try {
            $hospitals = Hospital::all();
            return response()->json($hospitals);
        } catch (\Exception $ex) {
            return response(400)->json($ex->getMessage());
        }
    }
}

app/Http/Controllers/HospitalController.php
<?php

namespace App\Http\Controllers;

use App\Traits\XIForm;
use Illuminate\Http\Request;
use Yajra\DataTables\DataTables;
use App\Http\Controllers\Controller;
use App\Http\Requests\HospitalRequest;
use Illuminate\Support\Facades\View;
use Kris\LaravelFormBuilder\FormBuilder;
use App\Models\Hospital;
use Illuminate\Support\Facades\DB;
use Proengsoft\JsValidation\Facades\JsValidatorFacade;

class HospitalController extends Controller
{
    private $module, $model, $form;
    protected $repository;
    use XIForm;

    public function __construct(Hospital $repository, FormBuilder $formBuilder)
    {
        $this->module = 'hospital';
        $this->repository = $repository;
        $this->formBuilder = $formBuilder;
        $this->form = 'App\Forms\HospitalForm';
        $this->formRequest = 'App\Http\Requests\HospitalRequest';
        $this->quotaFormRequest = 'App\Http\Requests\QuotaRequest';
        $this->quotaForm = 'App\Forms\QuotaForm';

        View::share('module', $this->module);
    }

    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index(Request $request)
    {
        if (!$request->user()->can($this->module . '.view')) return notPermited();

        if ($request->ajax()) {
            $data = $this->repository->orderBy('created_at', 'ASC');
            return DataTables::of($data)
                ->addColumn('action', function ($data) {
                    $buttons[] = ['type' => 'detail', 'route' => route($this->module . '.show', $data->id), 'label' => 'Detail', 'action' => 'primary', 'icon' => 'share'];
                    $buttons[] = ['type' => 'edit', 'route' => route($this->module . '.edit', $data->id), 'label' => 'Edit', 'icon' => 'edit'];
                    $buttons[] = ['type' => 'delete', 'label' => 'Delete', 'confirm' => 'Are you sure?', 'route' => route($this->module . '.destroy', $data->id)];

                    return $this->icon_button($buttons, false);
                })
                ->make();
        }
        return view('pages.' . $this->module . '.index');
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create(Request $request)
    {
        if (!$request->user()->can($this->module . '.create')) return notPermited();

        $data['form'] = $this->formBuilder->create($this->form, [
            'method' => 'POST',
            'url' => route($this->module . '.store')
        ]);
        $data['validator'] = JsValidatorFacade::formRequest($this->formRequest);

        return view('pages.' . $this->module . '.create', $data);
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(HospitalRequest $request)
    {
        if (!$request->user()->can($this->module . '.create')) return notPermited();

        try {
            DB::transaction(function () use ($request) {
                $data = $request->all();
                $post = $this->repository->create($data);
                gilog("Create " . $this->module, $post, $data);
            });
            flash('Success create ' . $this->module)->success();
        } catch (\Exception $ex) {
            flash($ex->getMessage())->error();
        }
        return redirect()->route($this->module . '.index');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show(Request $request, $id)
    {
        if (!$request->user()->can($this->module . '.view')) return notPermited();

        $get = $this->repository->find($id);
        $data['detail'] = $get;
        $detail = new Hospital();
        $data['shows'] = $detail->getLabels();

        $data['form'] = $this->formBuilder->create($this->quotaForm, [
            'method' => 'POST',
            'url' => route('quota.store')
        ]);
        $data['validator'] = JsValidatorFacade::formRequest($this->quotaFormRequest);


        return view('pages.' . $this->module . '.show', $data);
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit(Request $request, $id)
    {
        if (!$request->user()->can($this->module . '.update')) return notPermited();

        $get = $this->repository->find($id);
        $data['form'] = $this->formBuilder->create($this->form, [
            'method' => 'PUT',
            'url' => route($this->module . '.update', $id),
            'model' => $get
        ]);

        return view('pages.' . $this->module . '.create', $data);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  array  $id
     * @return \Illuminate\Http\Response
     */
    public function update(HospitalRequest $request, $id)
    {
        if (!$request->user()->can($this->module . '.update')) return notPermited();

        try {
            DB::transaction(function () use ($id, $request) {
                $input = $request->all();
                $post = $this->repository->find($id);
                $post->update($input);
                gilog("Create " . $this->module, $post, $input);
            });
            flash('Success update ' . $this->module)->success();
        } catch (\Exception $ex) {
            flash($ex->getMessage())->error();
        }
        return redirect()->route($this->module . '.index');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy(Request $request, $id)
    {
        if (!$request->user()->can($this->module . '.delete')) return notPermited('json');

        try {
            DB::transaction(function () use ($id) {
                $get = $this->repository->find($id);
                $get->delete($id);
                gilog("Delete " . $this->module, $get, ['notes' => @request('notes')]);
            });
            $data['message'] = 'Success delete ' . $this->module;
            $status = 200;
        } catch (\Exception $ex) {
            $data['message'] = $ex->getMessage();
            $status = 500;
        }
        return response()->json($data, $status);
    }
}

resources/views/pages/hospital/create.blade.php
@extends('layouts.app')
@section('content')
    <div class="container-fluid">
        <div class="row">
            <div class="col-12">
                <div class="card">
                    <div class="card-body">
                        <div class="row">
                            <div class="col-md-8">
                                <h4 class="card-title">Rumah Sakit</h4>
                                <h6 class="card-subtitle">Pengelolaan Rumah Sakit</h6>
                            </div>
                            <div class="col-md-4" align="right">
                                <a href="{{ route($module . '.index') }}" class="btn btn-danger btn-lg"><i
                                        class="m-r-10 mdi mdi-backspace"></i>Kembali</a>
                            </div>
                        </div>
                        <hr>
                        <div class="form">
                            {!! form($form) !!}
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
@stop

resources/views/pages/hospital/index.blade.php
@extends('layouts.app')
@section('content')
    <div class="container-fluid">
        <div class="row">
            <div class="col-12">
                <div class="card">
                    <div class="card-body">
                        <div class="row">
                            <div class="col-md-8">
                                <h4 class="card-title">Rumah Sakit</h4>
                                <h6 class="card-subtitle">Pengelolaan Rumah Sakit</h6>
                            </div>
                            @can('hospital.create')
                                <div class="col-md-4" align="right">
                                    <a href="{{ route($module . '.create') }}" class="btn btn-success btn-lg"><i
                                            class="fa fa-plus"></i> Tambah</a>
                                </div>
                            @endcan
                        </div>
                        <hr>
                        <div class="table-responsive">
                            <table class="table table-striped table-hover table-bordered data-table">
                                <thead>
                                    <tr>
                                        <th>Nama</th>
                                        <th>Alamat</th>
                                        <th>Aksi</th>
                                    </tr>
                                </thead>
                                <tbody>

                                </tbody>
                            </table>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
@stop
@push('js')
    <script>
        $(document).ready(function() {
            $('.data-table').DataTable({
                processing: true,
                serverSide: true,
                ajax: '{{ route($module . '.index') }}',
                columns: [{
                        data: 'name',
                        name: 'name'
                    },
                    {
                        data: 'address',
                        name: 'address'
                    },
                    {
                        data: 'action',
                        name: 'action',
                        "searchable": false
                    }
                ]
            });
        });
    </script>
@endpush

resources/views/pages/hospital/show.blade.php
@extends('layouts.app')
@section('content')
<div class="container-fluid">
    <div class="row">
        <div class="col-md-12 mb-3">
            <div class="card">
                <div class="card-body">
                    <div class="row">
                        <div class="col-md-8">
                            <h4 class="card-title">Rumah Sakit</h4>
                            <h6 class="card-subtitle">Detail Rumah Sakit</h6>
                        </div>
                        <div class="col-md-4" align="right">
                            <a href="{{ route($module . '.index') }}" class="btn btn-danger btn-lg"><i class="m-r-10 mdi mdi-backspace"></i>Kembali</a>
                        </div>
                    </div>
                    <hr>
                    <div class="form form-horizontal">
                        @foreach ($shows as $key => $item)
                        <div class="form-group row">
                            <label class="col-sm-2 col-form-label">{{ ucfirst($item) }}</label>
                            <div class="col-sm-10">
                                {{ $detail->{$key} }}
                            </div>
                        </div>
                        @endforeach
                    </div>
                </div>
            </div>
        </div>
    </div>

    <div class="row">
        <div class="col-12">
            <div class="card">
                <div class="card-body">
                    <div class="d-flex justify-content-between">
                        <div class="col-md-6">
                            <h4 class="card-title">Kuota</h4>
                            <h6 class="card-subtitle">Pengelolaan Kuota Rumah Sakit</h6>
                        </div>
                        <div class="d-flex">
                            @can('quota.create')
                            <div class="mr-2" align="right">
                                <button type="button" class="btn btn-success btn-lg" data-toggle="modal" data-target="#quotaModal"><i class="fa fa-plus"></i> Tambah</button>
                            </div>
                            @endcan
                        </div>
                    </div>
                    <hr>
                    <div class="table-responsive">
                        <table class="table table-striped table-hover table-bordered data-table">
                            <thead>
                                <tr>
                                    <th>Stase</th>
                                    <th>Kuota</th>
                                    <th>Aksi</th>
                                </tr>
                            </thead>
                            <tbody>

                            </tbody>
                        </table>
                    </div>
                </div>
            </div>
        </div>
    </div>

    <div class="modal fade" id="quotaModal" tabindex="-1" role="dialog" aria-labelledby="quotaModalLabel" aria-hidden="true">
        <div class="modal-dialog modal-dialog-centered">
            <div class="modal-content">
                <div class="modal-header">
                    <h5 class="modal-title" id="exampleModalLabel">Atur Kuota</h5>
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                    </button>
                </div>
                <div class="modal-body">
                    {!! form($form) !!}
                </div>
            </div>
        </div>
    </div>


</div>
@stop

@push('js')
<script>
    $(document).ready(function() {
        $('.data-table').DataTable({
            processing: true,
            serverSide: true,
            ajax: {
                type: "GET",
                url: '{{ route("quota.index") }}',
                data: {
                    _token: '{{ csrf_token() }}',
                    hospital_id: '{{ $detail->id }}'
                }
            },
            columns: [{
                    data: 'stase',
                    name: 'stase'
                },
                {
                    data: 'quota',
                    name: 'quota'
                },
                {
                    data: 'action',
                    name: 'action',
                    "searchable": false
                }
            ]
        });

        let isEdit = false
        let current_quota_id = 0
        $('#btn-add-quota').click(function() {
            const body = {
                hospital_id: '{{ $detail->id }}',
                stase_id: $('#stase_id').val(),
                quota: $('#quota').val()
            }
            
            if (!isEdit) {
                $.post('{{ route("quota.store") }}', body).done(function(data) {
                    $('#quotaModal').modal('hide')
                    $('.data-table').DataTable().ajax.reload()
                })
            } else {
                const url = '{{ url("quota/") }}/' + current_quota_id
                $.ajax({
                    url: url,
                    type: 'PUT',
                    data: body,
                    success: function(res) {
                        $('#quotaModal').modal('hide')
                        $('.data-table').DataTable().ajax.reload()
                    }
                })
            }
        })

        $('body').on('click', '.btn-edit', function() {
            isEdit = true
            const data = $(this).data('model')
            current_quota_id = data.id

            $('#quota').val(data.quota)
            $('#stase_id').val(data.stase_id).trigger('change')
        })

        $('#quotaModal').on('hidden.bs.modal', function () { // when modal is closed
            isEdit = false
            $('#quota').val(null)
            $('#stase_id').val(null).trigger('change')
        });
    });

</script>
@endpush