routes/web.php
<?php

use App\Http\Controllers\Api\ScheduleStudentController;
use App\Http\Controllers\Auth\GoogleController;
use App\Http\Controllers\BalanceController;
use App\Http\Controllers\HomeController;
use App\Http\Controllers\PermissionController;
use App\Http\Controllers\RoleController;
use App\Http\Controllers\UserController;
use App\Http\Controllers\CategoryController;
use App\Http\Controllers\GradeController;
use App\Http\Controllers\HospitalController;
use App\Http\Controllers\LevelController;
use App\Http\Controllers\ProductController;
use App\Http\Controllers\ScheduleController;
use App\Http\Controllers\QuotaController;
use App\Http\Controllers\StaseController;
use App\Http\Controllers\StudentController;
use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Auth::routes(['register' => false]);

Route::get('auth/google', [GoogleController::class, 'redirectToGoogle'])->name('auth.google');
Route::get('auth/google/callback', [GoogleController::class, 'handleGoogleCallback']);

Route::group(['middleware' => ['auth']], function () {
    Route::get('', [HomeController::class, 'index'])->name('home');
    Route::get('home/report', [HomeController::class, 'report'])->name('home.report');

    Route::patch('user/login-as/{id}', [UserController::class, 'loginAs'])->name('user.login-as');
    Route::get('report', [HomeController::class, 'report'])->name('home.report');
    Route::resource('user', UserController::class);
    Route::resource('permission', PermissionController::class);
    Route::resource('role', RoleController::class);
    Route::resource('student', StudentController::class);
    Route::resource('hospital', HospitalController::class);
    Route::resource('stase', StaseController::class);
    Route::resource('schedule', ScheduleController::class);
    Route::resource('level', LevelController::class);
    Route::resource('grade', GradeController::class);
    Route::post('schedule/select-student', [ScheduleController::class, 'select_student'])->name('schedule.select-student');
    Route::post('schedule/update-schedule-student/{id}', [ScheduleController::class, 'update_schedule_student'])->name('schedule.update-schedule-student');
    Route::get('schedule/{id}/data', [ScheduleController::class, 'data'])->name('schedule.data');
    Route::post('schedule/{id}/drag', [ScheduleController::class, 'drag'])->name('schedule.drag');
    Route::get('schedule/{id}/report', [ScheduleController::class, 'report'])->name('schedule.report');
    Route::get('schedule/{schedule_id}/report/{student_id}', [ScheduleController::class, 'reportDetail'])->name('schedule.report-detail');
    Route::get('schedule/{id}/fullscreen', [ScheduleController::class, 'fullscreen'])->name('schedule.fullscreen');

    Route::resource('quota', QuotaController::class);
    Route::post('students/import', [StudentController::class, 'import'])->name('students.import');

    Route::get('stase/{id}/student-list', [StaseController::class, 'studentList'])->name('stase.student-list');
    Route::get('level/schedule/{id}/student-list', [LevelController::class, 'studentList'])->name('level.student-list');
    Route::get('students/export', [StudentController::class, 'export'])->name('students.export');
    Route::get('schedules/export/{id}', [ScheduleController::class, 'export'])->name('schedules.export');

    //api
    Route::get('api/hospital', [HospitalController::class, 'index'])->name('api.hospital.index');
    Route::get('api/stase', [StaseController::class, 'index'])->name('api.stase.index');
    Route::post('api/schedule-student/store', [ScheduleStudentController::class, 'store'])->name('api.schedule-student.store');
    Route::put('api/schedule-student/store-new-student', [ScheduleStudentController::class, 'storeNewStudent'])->name('api.schedule-student.store-new-student');
    Route::delete('api/schedule-student/{id}', [ScheduleStudentController::class, 'destroy'])->name('api.schedule-student.destroy');
    Route::put('api/schedule-student/{id}', [ScheduleStudentController::class, 'update'])->name('api.schedule-student.update');
});

Route::get('check-time', function () {
    return date('Y-m-d H:i:s');
});

resources/views/layouts/app-without-sidebar.blade.php
<!DOCTYPE html>
<html dir="ltr" lang="en">

<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <!-- Tell the browser to be responsive to screen width -->
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="">
    <meta name="csrf-token" content="{{ csrf_token() }}">
    <!-- Favicon icon -->
    <link rel="icon" type="image/png" sizes="16x16" href="{{ asset('assets/images/favicon.png') }}">
    <title>Koas Management APP</title>
    <!-- Custom CSS -->
    {{-- <link href="{{ asset('assets/libs/chartist/dist/chartist.min.css') }}" rel="stylesheet"> --}}
    <link href="{{ asset('assets/extra-libs/c3/c3.min.css') }}" rel="stylesheet" type="text/css">
    <link href="{{ asset('assets/libs/morris.js/morris.css') }}" rel="stylesheet" type="text/css">
    <!-- Custom CSS -->
    <link href="{{ asset('dist/css/style.min.css') }}" rel="stylesheet" type="text/css">
    <!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
    <!--[if lt IE 9]>
    <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
    <script src="https://oss.maxcdn.com/libs/respond.js/1.4.2/respond.min.js"></script>
    <![endif]-->

    <link href="{{ asset('assets/libs/select2/dist/css/select2.min.css') }}" rel="stylesheet" type="text/css">
    <link href="{{ asset('assets/libs/sweetalert2/dist/sweetalert2.min.css') }}" rel="stylesheet" type="text/css">
    <link href="{{ asset('assets/libs/datatables.net-bs4/css/dataTables.bootstrap4.css') }}" rel="stylesheet"
        type="text/css">
    <script src="{{ asset('assets/libs/jquery/dist/jquery.min.js') }}"></script>
    <link href="https://unpkg.com/gijgo@1.9.13/css/gijgo.min.css" rel="stylesheet" type="text/css" />
    <link
        href="{{ asset('assets/libs/bootstrap-material-datetimepicker/css/bootstrap-material-datetimepicker.css') }}"
        rel="stylesheet" type="text/css">
    <link href="{{ asset('assets/libs/select2/dist/css/select2.min.css') }}" rel="stylesheet" type="text/css">
    <link href="{{ asset('dist/css/main.css') }}" rel="stylesheet" type="text/css">
    @stack('css')
</head>

<body>
    <!-- ============================================================== -->
    <!-- Preloader - style you can find in spinners.css -->
    <!-- ============================================================== -->
    <div class="preloader">
        <div class="lds-ripple">
            <div class="lds-pos"></div>
            <div class="lds-pos"></div>
        </div>
    </div>
    <!-- ============================================================== -->
    <!-- Main wrapper - style you can find in pages.scss -->
    <!-- ============================================================== -->
    <div id="main-wrapper">
        <br>
        <!-- ============================================================== -->
        <!-- Topbar header - style you can find in pages.scss -->
        <!-- ============================================================== -->
        <!-- ============================================================== -->
        <!-- End Topbar header -->
        <!-- ============================================================== -->
        <!-- ============================================================== -->
        <!-- Left Sidebar - style you can find in sidebar.scss  -->
        <!-- ============================================================== -->
        {{-- @include('layouts.sidebar') --}}
        <!-- ============================================================== -->
        <!-- End Left Sidebar - style you can find in sidebar.scss  -->
        <!-- ============================================================== -->
        <!-- ============================================================== -->
        <!-- Page wrapper  -->
        <!-- ============================================================== -->
        @include('flash::message')
        <!-- ============================================================== -->
        <!-- Bread crumb and right sidebar toggle -->
        <!-- ============================================================== -->
        <!-- ============================================================== -->
        <!-- End Bread crumb and right sidebar toggle -->
        <!-- ============================================================== -->
        <!-- ============================================================== -->
        <!-- Container fluid  -->
        <!-- ============================================================== -->
        @yield('content')
        <!-- ============================================================== -->
        <!-- End Container fluid  -->
        <!-- ============================================================== -->
        <!-- ============================================================== -->
        <!-- footer -->
        <!-- ============================================================== -->
        <footer class="footer text-center">
            All Rights Reserved
        </footer>
        <!-- ============================================================== -->
        <!-- End footer -->
        <!-- ============================================================== -->
        <!-- ============================================================== -->
        <!-- End Page wrapper  -->
        <!-- ============================================================== -->
    </div>

    <script src="{{ asset('assets/libs/popper.js/dist/umd/popper.min.js') }}"></script>
    <script src="{{ asset('assets/libs/bootstrap/dist/js/bootstrap.min.js') }}"></script>
    <script src="{{ asset('dist/js/app.min.js') }}"></script>
    <script src="{{ asset('dist/js/app.init.js') }}"></script>
    <script src="{{ asset('dist/js/app-style-switcher.js') }}"></script>
    <script src="{{ asset('assets/libs/perfect-scrollbar/dist/perfect-scrollbar.jquery.min.js') }}"></script>
    <script src="{{ asset('assets/extra-libs/sparkline/sparkline.js') }}"></script>
    <script src="{{ asset('dist/js/waves.js') }}"></script>
    <script src="{{ asset('dist/js/sidebarmenu.js') }}"></script>
    <script src="{{ asset('dist/js/custom.min.js') }}"></script>
    <script src="{{ asset('assets/extra-libs/c3/d3.min.js') }}"></script>
    <script src="{{ asset('assets/extra-libs/c3/c3.min.js') }}"></script>
    <script src="{{ asset('assets/libs/raphael/raphael.min.js') }}"></script>
    <script src="{{ asset('assets/libs/morris.js/morris.min.js') }}"></script>

    <script src="{{ asset('assets/extra-libs/DataTables/datatables.min.js') }}" type="text/javascript"></script>
    <script src="{{ asset('assets/libs/select2/dist/js/select2.full.min.js') }}" type="text/javascript"></script>
    <script src="{{ asset('assets/libs/select2/dist/js/select2.min.js') }}" type="text/javascript"></script>
    <script src="{{ asset('vendor/jsvalidation/js/jsvalidation.min.js') }}" type="text/javascript"></script>
    <script src="{{ asset('assets/libs/sweetalert2/dist/sweetalert2.all.min.js') }}" type="text/javascript"></script>
    <script src="{{ asset('assets/libs/moment/moment.js') }}" type="text/javascript"></script>
    <script src="{{ asset('assets/libs/bootstrap-material-datetimepicker/js/bootstrap-material-datetimepicker.js') }}"
        type="text/javascript"></script>

    <script src="https://unpkg.com/gijgo@1.9.13/js/gijgo.min.js" type="text/javascript"></script>


    <script>
        var dataTable = '',
            drEvent = '';
    </script>

    {!! @$validator !!}
    <script>
        $(function() {
            // $('.data-table').DataTable();
            // drEvent = $('.dropify').dropify();
            $('#flash-overlay-modal').modal();
            $(".select2").select2({
                width: 'resolve'
            });
            $(".select2-tags").select2({
                tags: true
            });
            // $.fn.datetimepicker.Constructor.Default = $.extend({}, $.fn.datetimepicker.Constructor.Default, {
            //     icons: {
            //         time: 'fa fa-clock',
            //         date: 'fa fa-calendar',
            //         up: 'fa fa-arrow-up',
            //         down: 'fa fa-arrow-down',
            //         previous: 'fa fa-chevron-left',
            //         next: 'fa fa-chevron-right',
            //         today: 'fa fa-calendar-check-o',
            //         clear: 'fa fa-trash',
            //         close: 'fa fa-times'
            //     },
            //     format: 'YYYY-MM-DD hh:mm:ss'
            // });
            $('form').on('keyup change paste',
                'input:not(".skip-change"), select:not(".skip-change"), textarea:not(".skip-change")',
                function() {
                    $(this).data("changed", true);
                });
            // $("input.v-nospace").limitkeypress({
            //     rexp: /^\S*$/
            // });
            $(".datepicker-input").datepicker({
                uiLibrary: 'bootstrap4',
                format: 'yyyy-mm-dd'
            });
            $("form").submit(function() {
                if ($(this).valid()) {
                    $.each($(this).find("input.number"), function(indexInArray, valueOfElement) {
                        if ($(this).val() != '') {
                            $(this).removeClass('number');
                            $(this).val($(this).val().replace(/,/g, ""));
                        }
                    });
                }

            });
        });
    </script>
    @stack('js')
    <script src="{{ asset('dist/js/main.js') }}"></script>
</body>

</html>

resources/views/layouts/app.blade.php
<!DOCTYPE html>
<html dir="ltr" lang="en">

<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <!-- Tell the browser to be responsive to screen width -->
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="">
    <meta name="csrf-token" content="{{ csrf_token() }}">
    <!-- Favicon icon -->
    <link rel="icon" type="image/png" sizes="16x16" href="{{ asset('assets/images/favicon.png') }}">
    <title>Koas Management APP</title>
    <!-- Custom CSS -->
    {{-- <link href="{{ asset('assets/libs/chartist/dist/chartist.min.css') }}" rel="stylesheet"> --}}
    <link href="{{ asset('assets/extra-libs/c3/c3.min.css') }}" rel="stylesheet" type="text/css">
    <link href="{{ asset('assets/libs/morris.js/morris.css') }}" rel="stylesheet" type="text/css">
    <!-- Custom CSS -->
    <link href="{{ asset('dist/css/style.min.css') }}" rel="stylesheet" type="text/css">
    <!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
    <!--[if lt IE 9]>
    <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
    <script src="https://oss.maxcdn.com/libs/respond.js/1.4.2/respond.min.js"></script>
    <![endif]-->

    <link href="{{ asset('assets/libs/select2/dist/css/select2.min.css') }}" rel="stylesheet" type="text/css">
    <link href="{{ asset('assets/libs/sweetalert2/dist/sweetalert2.min.css') }}" rel="stylesheet" type="text/css">
    <link href="{{ asset('assets/libs/datatables.net-bs4/css/dataTables.bootstrap4.css') }}" rel="stylesheet"
        type="text/css">
    <script src="{{ asset('assets/libs/jquery/dist/jquery.min.js') }}"></script>
    <link href="https://unpkg.com/gijgo@1.9.13/css/gijgo.min.css" rel="stylesheet" type="text/css" />
    <link
        href="{{ asset('assets/libs/bootstrap-material-datetimepicker/css/bootstrap-material-datetimepicker.css') }}"
        rel="stylesheet" type="text/css">
    <link href="{{ asset('assets/libs/select2/dist/css/select2.min.css') }}" rel="stylesheet" type="text/css">
    <link href="{{ asset('dist/css/main.css') }}" rel="stylesheet" type="text/css">
    @stack('css')
</head>

<body>
    <!-- ============================================================== -->
    <!-- Preloader - style you can find in spinners.css -->
    <!-- ============================================================== -->
    <div class="preloader">
        <div class="lds-ripple">
            <div class="lds-pos"></div>
            <div class="lds-pos"></div>
        </div>
    </div>
    <!-- ============================================================== -->
    <!-- Main wrapper - style you can find in pages.scss -->
    <!-- ============================================================== -->
    <div id="main-wrapper">
        <!-- ============================================================== -->
        <!-- Topbar header - style you can find in pages.scss -->
        <!-- ============================================================== -->
        @include('layouts.header')
        <!-- ============================================================== -->
        <!-- End Topbar header -->
        <!-- ============================================================== -->
        <!-- ============================================================== -->
        <!-- Left Sidebar - style you can find in sidebar.scss  -->
        <!-- ============================================================== -->
        @include('layouts.sidebar')
        <!-- ============================================================== -->
        <!-- End Left Sidebar - style you can find in sidebar.scss  -->
        <!-- ============================================================== -->
        <!-- ============================================================== -->
        <!-- Page wrapper  -->
        <!-- ============================================================== -->
        <div class="page-wrapper">
            @include('flash::message')
            <!-- ============================================================== -->
            <!-- Bread crumb and right sidebar toggle -->
            <!-- ============================================================== -->
            @include('layouts.breadcrumb')
            <!-- ============================================================== -->
            <!-- End Bread crumb and right sidebar toggle -->
            <!-- ============================================================== -->
            <!-- ============================================================== -->
            <!-- Container fluid  -->
            <!-- ============================================================== -->
            @yield('content')
            <!-- ============================================================== -->
            <!-- End Container fluid  -->
            <!-- ============================================================== -->
            <!-- ============================================================== -->
            <!-- footer -->
            <!-- ============================================================== -->
            <footer class="footer text-center">
                All Rights Reserved
            </footer>
            <!-- ============================================================== -->
            <!-- End footer -->
            <!-- ============================================================== -->
        </div>
        <!-- ============================================================== -->
        <!-- End Page wrapper  -->
        <!-- ============================================================== -->
    </div>

    <script src="{{ asset('assets/libs/popper.js/dist/umd/popper.min.js') }}"></script>
    <script src="{{ asset('assets/libs/bootstrap/dist/js/bootstrap.min.js') }}"></script>
    <script src="{{ asset('dist/js/app.min.js') }}"></script>
    <script src="{{ asset('dist/js/app.init.js') }}"></script>
    <script src="{{ asset('dist/js/app-style-switcher.js') }}"></script>
    <script src="{{ asset('assets/libs/perfect-scrollbar/dist/perfect-scrollbar.jquery.min.js') }}"></script>
    <script src="{{ asset('assets/extra-libs/sparkline/sparkline.js') }}"></script>
    <script src="{{ asset('dist/js/waves.js') }}"></script>
    <script src="{{ asset('dist/js/sidebarmenu.js') }}"></script>
    <script src="{{ asset('dist/js/custom.min.js') }}"></script>
    <script src="{{ asset('assets/extra-libs/c3/d3.min.js') }}"></script>
    <script src="{{ asset('assets/extra-libs/c3/c3.min.js') }}"></script>
    <script src="{{ asset('assets/libs/raphael/raphael.min.js') }}"></script>
    <script src="{{ asset('assets/libs/morris.js/morris.min.js') }}"></script>

    <script src="{{ asset('assets/extra-libs/DataTables/datatables.min.js') }}" type="text/javascript"></script>
    <script src="{{ asset('assets/libs/select2/dist/js/select2.full.min.js') }}" type="text/javascript"></script>
    <script src="{{ asset('assets/libs/select2/dist/js/select2.min.js') }}" type="text/javascript"></script>
    <script src="{{ asset('vendor/jsvalidation/js/jsvalidation.min.js') }}" type="text/javascript"></script>
    <script src="{{ asset('assets/libs/sweetalert2/dist/sweetalert2.all.min.js') }}" type="text/javascript"></script>
    <script src="{{ asset('assets/libs/moment/moment.js') }}" type="text/javascript"></script>
    <script src="{{ asset('assets/libs/bootstrap-material-datetimepicker/js/bootstrap-material-datetimepicker.js') }}"
        type="text/javascript">
    </script>

    <script src="https://unpkg.com/gijgo@1.9.13/js/gijgo.min.js" type="text/javascript"></script>


    <script>
        var dataTable = '',
            drEvent = '';
    </script>

    {!! @$validator !!}
    <script>
        $(function() {
            // $('.data-table').DataTable();
            // drEvent = $('.dropify').dropify();
            $('#flash-overlay-modal').modal();
            $(".select2").select2({
                width: 'resolve'
            });
            $(".select2-tags").select2({
                tags: true
            });
            // $.fn.datetimepicker.Constructor.Default = $.extend({}, $.fn.datetimepicker.Constructor.Default, {
            //     icons: {
            //         time: 'fa fa-clock',
            //         date: 'fa fa-calendar',
            //         up: 'fa fa-arrow-up',
            //         down: 'fa fa-arrow-down',
            //         previous: 'fa fa-chevron-left',
            //         next: 'fa fa-chevron-right',
            //         today: 'fa fa-calendar-check-o',
            //         clear: 'fa fa-trash',
            //         close: 'fa fa-times'
            //     },
            //     format: 'YYYY-MM-DD hh:mm:ss'
            // });
            $('form').on('keyup change paste',
                'input:not(".skip-change"), select:not(".skip-change"), textarea:not(".skip-change")',
                function() {
                    $(this).data("changed", true);
                });
            // $("input.v-nospace").limitkeypress({
            //     rexp: /^\S*$/
            // });
            $(".datepicker-input").datepicker({
                uiLibrary: 'bootstrap4',
                format: 'yyyy-mm-dd'
            });
            $("form").submit(function() {
                if ($(this).valid()) {
                    $.each($(this).find("input.number"), function(indexInArray, valueOfElement) {
                        if ($(this).val() != '') {
                            $(this).removeClass('number');
                            $(this).val($(this).val().replace(/,/g, ""));
                        }
                    });
                }

            });
        });
    </script>
    @stack('js')
    <script src="{{ asset('dist/js/main.js') }}"></script>
</body>

</html>

resources/views/layouts/breadcrumb.blade.php
<div class="page-breadcrumb">
    <div class="row">
        <div class="col-5 align-self-center">
            <h4 class="page-title">Dashboard</h4>
            <div class="d-flex align-items-center">

            </div>
        </div>
        <div class="col-7 align-self-center">
            <div class="d-flex no-block justify-content-end align-items-center">
                <nav aria-label="breadcrumb">
                    <ol class="breadcrumb">
                        <li class="breadcrumb-item">
                            <a href="#">Home</a>
                        </li>
                        <li class="breadcrumb-item active" aria-current="page">Library</li>
                    </ol>
                </nav>
            </div>
        </div>
    </div>
</div>

resources/views/layouts/sidebar.blade.php
<aside class="left-sidebar">
    <div class="scroll-sidebar">
        <nav class="sidebar-nav">
            <ul id="sidebarnav">
                <li class="sidebar-item">
                    <a class="sidebar-link waves-effect waves-dark" href="{{ route('home') }}" aria-expanded="false">
                        <i class="icon-Car-Wheel"></i>
                        <span class="hide-menu">Dashboard </span>
                    </a>
                </li>

                @can('user.view', 'permission.view', 'role.view')
                    <li class="sidebar-item">
                        <a class="sidebar-link has-arrow waves-effect waves-dark" href="javascript:void(0)"
                            aria-expanded="false">
                            <i class="fas fa-user-circle"></i>
                            <span class="hide-menu">User </span>
                        </a>
                        <ul aria-expanded="false" class="collapse first-level">
                            @can('user.view')
                                <li class="sidebar-item">
                                    <a href="{{ route('user.index') }}" class="sidebar-link">
                                        <i class="mdi mdi-email"></i>
                                        <span class="hide-menu"> User List </span>
                                    </a>
                                </li>
                            @endcan

                            @can('permission.view')
                                <li class="sidebar-item">
                                    <a href="{{ route('permission.index') }}" class="sidebar-link">
                                        <i class="mdi mdi-adjust"></i><span class="hide-menu">User Permission</span>
                                    </a>
                                </li>
                            @endcan

                            @can('role.view')
                                <li class="sidebar-item">
                                    <a href="{{ route('role.index') }}" class="sidebar-link"><i
                                            class="mdi mdi-adjust"></i><span class="hide-menu">User Role</span>
                                    </a>
                                </li>
                            @endcan
                        </ul>
                    </li>
                @endcan

                @can('balance.view')
                    <li class="sidebar-item">
                        <a class="sidebar-link has-arrow waves-effect waves-dark" href="javascript:void(0)"
                            aria-expanded="false"><i class="mdi mdi-cash-multiple"></i><span
                                class="hide-menu">Keuangan</span></a>

                        <ul aria-expanded="false" class="collapse first-level">
                            @can('balance.view')
                                <li class="sidebar-item">
                                    <a href="{{ route('balance.index') }}" class="sidebar-link">
                                        <i class="mdi mdi-cash-multiple"></i>
                                        <span class="hide-menu"> Riwayat Saldo</span>
                                    </a>
                                </li>
                            @endcan
                        </ul>
                    </li>
                @endcan

                @can('category.view')
                <li class="sidebar-item">
                    <a href="{{ route('category.index') }}" class="sidebar-link">
                        <i class="mdi mdi-account"></i>
                        <span class="hide-menu"> Category </span>
                    </a>
                </li>
                @endcan

                @can('student.view')
                <li class="sidebar-item">
                    <a href="{{ route('student.index') }}" class="sidebar-link ml-1">
                        <i class="fas fa-user-plus"></i>
                        <span class="hide-menu"> Mahasiswa </span>
                    </a>
                </li>
                @endcan

                @can('hospital.view')
                <li class="sidebar-item">
                    <a href="{{ route('hospital.index') }}" class="sidebar-link">
                        <i class="fas fa-notes-medical"></i>
                        <span class="hide-menu"> Rumah Sakit </span>
                    </a>
                </li>
                @endcan

                @can('stase.view')
                <li class="sidebar-item">
                    <a href="{{ route('stase.index') }}" class="sidebar-link">
                        <i class="fas fa-sticky-note"></i>
                        <span class="hide-menu"> Stase </span>
                    </a>
                </li>
                @endcan
                @can('level.view')
                <li class="sidebar-item">
                    <a href="{{ route('level.index') }}" class="sidebar-link">
                        <i class="fas fa-sort-numeric-up"></i>
                        <span class="hide-menu"> Semester </span>
                    </a>
                </li>
                @endcan
                @can('grade.view')
                <li class="sidebar-item">
                    <a href="{{ route('grade.index') }}" class="sidebar-link">
                        <i class="fas fa-sticky-note"></i>
                        <span class="hide-menu"> Angkatan </span>
                    </a>
                </li>
                @endcan
                @can('schedule.view')
                <li class="sidebar-item">
                    <a href="{{ route('schedule.index') }}" class="sidebar-link">
                        <i class="fas fa-calendar-alt"></i>
                        <span class="hide-menu"> Schedule </span>
                    </a>
                </li>
                @endcan
            </ul>
        </nav>
    </div>
</aside>